"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.appRouterV1 = void 0;
const controllers_1 = require("../../controllers");
const userRouter_1 = require("./userRouter");
const uploadFileRoute_1 = require("./uploadFileRoute");
const marginRouter_1 = require("./marginRouter");
const bahanRouter_1 = require("./bahanRouter");
const biayaKerjaRouter_1 = require("./biayaKerjaRouter");
const customerRouter_1 = require("./customerRouter");
const pegawaiRouter_1 = require("./pegawaiRouter");
const supplierRouter_1 = require("./supplierRouter");
const warnaRouter_1 = require("./warnaRouter");
const projectBahanRouter_1 = require("./projectBahanRouter");
const projectBarangRouter_1 = require("./projectBarangRouter");
const projectCetakRouter_1 = require("./projectCetakRouter");
const projectKerjaRouter_1 = require("./projectKerjaRouter");
const projectBahanLainRouter_1 = require("./projectBahanLainRouter");
const projectsRouter_1 = require("./projectsRouter");
const appRouterV1 = (app) => {
    app.get('/api/v1', async (req, res) => await (0, controllers_1.index)(req, res));
    (0, userRouter_1.userRoutes)(app);
    (0, uploadFileRoute_1.uploadFileRoutes)(app);
    (0, bahanRouter_1.bahanRoutes)(app);
    (0, marginRouter_1.marginRoutes)(app);
    (0, biayaKerjaRouter_1.biayaKerjaRoutes)(app);
    (0, customerRouter_1.customersRoutes)(app);
    (0, pegawaiRouter_1.pegawaiRoutes)(app);
    (0, supplierRouter_1.supplierRoutes)(app);
    (0, warnaRouter_1.warnaRoutes)(app);
    (0, projectBahanRouter_1.projectBahanRoutes)(app);
    (0, projectBarangRouter_1.projectBarangRoutes)(app);
    (0, projectCetakRouter_1.projectCetakRoutes)(app);
    (0, projectKerjaRouter_1.projectKerjaRoutes)(app);
    (0, projectBahanLainRouter_1.projectBahanLainRoutes)(app);
    (0, projectsRouter_1.projectRoutes)(app);
};
exports.appRouterV1 = appRouterV1;
